# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTM0YzM1MmRlYTFlYTZkNjRkZjEzZGFlMzcwZjc2ZDU3MzBkZmEzYTc1YmNmMDcwNjJjMTJmNjNmYjkxYjExOWU4OTg4MzJlMjFiYTA0MGVkNzNhMjQwNDdlMGE2ZGI2YWRmMzBmYjM1ZjZkMjc2Mjk3NTJlNTc3YTdlYjg0NmM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
